### ISSUE TITLE
Current master branch build fails to generate rootfs

### ISSUE THREAD

**Issue by jleidel** [riscv/meta-riscv#26] opened 2018-08-27 19:30 UTC
Current master branch (08/27/2018) fails to generate a rootfs.  Error message: 

WARNING: core-image-full-cmdline-1.0-r0 do_rootfs: Intentionally failing postinstall scriptlets of ['locale-base-en-us', 'locale-base-en-gb'] to defer them to first boot is deprecated. Please place them into pkg_postinst_ontarget_${PN} ().
If deferring to first boot wasn't the intent, then scriptlet failure may mean an issue in the recipe, or a regression elsewhere.
Details of the failure are in ~/riscv-yocto/build/tmp/work/qemuriscv64-poky-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: The postinstall intercept hook 'update_gio_module_cache' failed, details in ~/riscv-yocto/build/tmp/work/qemuriscv64-poky-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: ~/riscv-yocto/build/tmp/work/qemuriscv64-poky-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.29322
ERROR: Task (!/riscv-yocto/poky/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs) failed with exit code '1'

**Comment by kraj** [comment] 2018-08-29 02:06
I can reproduce this. It seems that we are not able to run qemu-user during build which is supposed to pregenerate these files. Recent image QA checks have started to catch this. I think image should still be building even after these diags. Isn't that the case ?

**Comment by kraj** [comment] 2018-08-29 02:09
Can you try to revert https://github.com/riscv/meta-riscv/commit/dcb61db68d2e73ed5d8ad3f075ae01de2e78f8ba

and see if that helps ?

**Comment by pino-kim** [comment] 2018-08-29 02:32
Dear @kraj, @jleidel.
I builded dcb61db  yesterday and meet same issue.

**Comment by kraj** [comment] 2018-08-29 03:07
@pino-kim so you can confirm it was a problem before us changing
to using upstream qemu ?

**Comment by pino-kim** [comment] 2018-08-29 05:10
I love this repository because I send first PR here.
So every pr is comming up. I do git clone and sync, build it again.
My latest build date is Aug 28th after we comment pr 552526019de9cf5d3061553e5c432ae8c75b430f is merged.
But make it clear. check my latest commit, when I back to home right away.

To summarize the issues I encountered
3d52a339fe378be2b1d67d163626d379112affe0 : kernel 4.18-r7  fetch well but kernel build issue. so I commented it linux-riscv github.  

e64b2ee4de0ef75429a938cc748d66ee16911c17 : kernel4.18  build well but meet same issue above.

552526019de9cf5d3061553e5c432ae8c75b430f and
dcb61db68d2e73ed5d8ad3f075ae01de2e78f8ba : after we talk about QEMU 3.0 and I build it. meet same issue above.

thank you.

**Comment by jleidel** [comment] 2018-08-29 12:06
I can't confirm the bug in dcb61db; I dropped my original source to pull a refresh copy and rebase on dcb61db.  The build instructions from the README.md now fail.  This is tracked in Issue #28

**Comment by jleidel** [comment] 2018-08-29 21:11
confirming on today's master branch that the bugs still exist.  the image is not created.  attempting to run qemu gives the following errors: 

runqemu - INFO - Running bitbake -e...
ls: cannot access '/hdd/home/jleidel/dev/working/yocto/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/*.qemuboot.conf': No such file or directory
runqemu - ERROR - Command 'ls -t /hdd/home/jleidel/dev/working/yocto/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/*.qemuboot.conf' returned non-zero exit status 2
runqemu - INFO - Cleaning up

**Comment by kraj** [comment] 2018-08-30 01:14
proposed patches  to OE-Core

http://lists.openembedded.org/pipermail/openembedded-core/2018-August/154993.html

 fixes the problem, You can cherry-pick them or wait until they land in master.

**Comment by uh13719** [comment] 2018-09-03 19:37
I am not sure if the error below this is related to this issue. But I have tried applying the patch to my build with no effect. 

ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: The postinstall intercept hook 'update_pixbuf_cache' failed,

can someone please help me?

**Comment by kraj** [comment] 2018-09-04 20:53
Can you retry with todays master ?

**Comment by jleidel** [comment] 2018-09-05 11:40
The build still fails: 

WARNING: core-image-full-cmdline-1.0-r0 do_rootfs: busybox.postinst returned 1, marking as unpacked only, configuration required on target.
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Postinstall scriptlets of ['busybox'] have failed. If the intention is to defer them to first boot,                                          then please place them into pkg_postinst_ontarget_${PN} ().                                    Deferring to first boot via 'exit 1' is no longer supported.                                   Details of the failure are in /hdd/home/jleidel/dev/working/yocto/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /hdd/home/jleidel/dev/working/yocto/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.6705
ERROR: Task (/hdd/home/jleidel/dev/working/yocto/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs) failed with exit code '1'

**Comment by kraj** [comment] 2018-09-05 14:54
Please cherry-pick this commit to openembedded-core

https://patchwork.openembedded.org/patch/154406/

**Comment by kraj** [comment] 2018-09-05 20:52
Latest master has this fix now http://git.openembedded.org/openembedded-core/commit/?id=ef11c54ba99af261a70ec31091216cdd1556da24

with this you should be able to build the images again. Please update and retry

**Comment by jleidel** [comment] 2018-09-06 01:06
The build still fails: 

ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: The postinstall intercept hook 'update_pixbuf_cache' failed, details in /hdd/home/jleidel/dev/working/yocto/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /hdd/home/jleidel/dev/working/yocto/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.14184
ERROR: Task (/hdd/home/jleidel/dev/working/yocto/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs) failed with exit code '1'

**Comment by kraj** [comment] 2018-09-06 02:14
thanks, it seems we need more fixes. Reason is that qemu-user is failing probably a risc-v qemu issue.
we need to dig

**Comment by pino-kim** [comment] 2018-09-06 06:29
[rootfs_log_20180906.txt](https://github.com/riscv/meta-riscv/files/2355758/rootfs_log_20180906.txt)
I build and get fail log too.

ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: The postinstall intercept hook 'update_font_cache' failed, details in /home/pino/workspace/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/pino/workspace/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.14230
ERROR: Task (/home/pino/workspace/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs) failed with exit code '1'

**Comment by lewishanly** [comment] 2018-09-20 12:53
log.do_rootfs.28664

Fail Log I am seeing:
NOTE: Running intercept scripts:
NOTE: > Executing update_pixbuf_cache intercept ...
NOTE: Exit code 2. Output:
/home/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/intercept_scripts-2c03b46bc7941049a88b6c1719c35aade81b0ce5490421e7cca768bf8beb0d01/update_pixbuf_cache: 8: /home/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/intercept_scripts-2c03b46bc7941049a88b6c1719c35aade81b0ce5490421e7cca768bf8beb0d01/update_pixbuf_cache: cannot create /home//riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/rootfs/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/../loaders.cache: Directory nonexistent

ERROR: The postinstall intercept hook 'update_pixbuf_cache' failed, details in /home/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs
DEBUG: Python function do_rootfs finished
ERROR: Function failed: do_rootfs

**Comment by kraj** [comment] 2018-09-20 13:46
Can you try adding
```
PACKAGE_CLASSES = "package_rpm"
```

in local.conf and see if that helps ?

**Comment by pino-kim** [comment] 2018-09-20 13:48
dear @kraj
I will try
and report it soon.

**Comment by pino-kim** [comment] 2018-09-20 22:32
try change in `local.conf`
`PACKAGE_CLASSES = "package_rpm`

ERROR: corerror: core-image-full-cmdline-1.0-r0 do_rootfs: The postinstall intercept hook 'update_font_cache' failed, details in /home/pino/workspace/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/pino/workspace/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.16797
ERROR: Task (/home/pino/workspace/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2913 tasks of which 5 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/pino/workspace/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by kraj** [comment] 2018-09-21 01:01
hmm I just build latest master and dont see this error. Can you post the Build Configuration which is printed by bitbake at the beginning of build

**Comment by pino-kim** [comment] 2018-09-21 02:19
@kraj 
hmm really? fine news
I build it yesterday. So I will rebuild it report soon. 
you want to see. Host bitbake information when build is start?

**Comment by pino-kim** [comment] 2018-09-21 11:21
@kraj 
I set my pc like Readme file.
and change `PACKAGE_CLASSES = "package_rpm"`  in  `riscv-yocto/build/conf/local.conf`

Build Configuration:
BB_VERSION           = "1.39.1"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "riscv64-oe-linux"
MACHINE              = "qemuriscv64"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "riscv64 littleendian"
meta                 = "work:957a2f95b839f2d871c658d6e8ea8c0f4d6c41e5"
meta-oe              
meta-multimedia      
meta-python          
meta-networking      = "work:a06c29be2f5bc204f965ee07298c34232c5c39fc"
meta-riscv           = "work:3048b416520d3607bbe3909002175f952c40e1a4"

Initialising tasks: 100% |############################################################################################################| Time: 0:00:02
Sstate summary: Wanted 972 Found 0 Missed 972 Current 0 (0% match, 0% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: The postinstall intercept hook 'update_font_cache' failed, details in /home/pino/workspace/opensource_work/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs
ERROR: core-image-full-cmdline-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/pino/workspace/opensource_work/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-full-cmdline/1.0-r0/temp/log.do_rootfs.19363
ERROR: Task (/home/pino/workspace/opensource_work/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2885 tasks of which 5 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/pino/workspace/opensource_work/riscv-yocto/openembedded-core/meta/recipes-extended/images/core-image-full-cmdline.bb:do_rootfs
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by pino-kim** [comment] 2018-09-21 15:57
[log_do_rootfs.txt](https://github.com/riscv/meta-riscv/files/2406067/log_do_rootfs.txt)
@kraj
what's your distro  to build?

**Closed** 2018-09-24 15:46 UTC
Labels: bug
